from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboards, name='dashboards'),
    path('listanalytics/', views.list_analytics, name='list_analytics'),
    path('<int:analytic_id>/trend/', views.trend, name='trend'),
    path('<int:analytic_id>/trend/<int:tab>/', views.trend, name='trend'),
    path('events/<int:analytic_id>/<str:eventdate>/<str:endpointname>/', views.events, name='events'),
    path('events/<int:analytic_id>/<str:eventdate>/', views.events, name='events'),
    path('events/<int:analytic_id>/', views.events, name='events'),
    path('storyline/<str:storylineids>/<str:eventdate>/', views.storyline, name='storyline'),
    path('<int:analytic_id>/detail/', views.analyticdetail, name='analyticdetail'),
    path('debug', views.debug, name='debug'),
    path('timeline', views.timeline, name='timeline'),
    path('<int:analytic_id>/regen/', views.regen, name='regen'),
    path('cancelregen/<str:taskid>/', views.cancelregen, name='cancelregen'),
    path('<int:analytic_id>/progress/', views.progress, name='progress'),
    path('<int:analytic_id>/deletestats/', views.deletestats, name='deletestats'),
    path('netview', views.netview, name='netview'),
    path('about', views.about, name='about'),
    path('notifications', views.notifications, name='notifications'),
    path('managecampaigns', views.managecampaigns, name='managecampaigns'),
    path('regencampaign/<str:campaign_name>/', views.regencampaign, name='regencampaign'),
    path('regencampaignstatus/<str:campaign_name>/', views.regencampaignstatus, name='regencampaignstatus'),
    path('review/<int:analytic_id>/', views.analytic_review, name='analytic_review'),

    path('db_totalnumberanalytics/', views.db_totalnumberanalytics, name='db_totalnumberanalytics'),
    path('db_analyticsrunintodaycampaign/', views.db_analyticsrunintodaycampaign, name='db_analyticsrunintodaycampaign'),
    path('db_analyticsmatchingintodaycampaign/', views.db_analyticsmatchingintodaycampaign, name='db_analyticsmatchingintodaycampaign'),
    path('db_analyticstoreview/', views.db_analyticstoreview, name='db_analyticstoreview'),
    path('db_archivedanalytics/', views.db_archivedanalytics, name='db_archivedanalytics'),
    path('db_analyticsbystatus/', views.db_analyticsbystatus, name='db_analyticsbystatus'),
    path('db_analyticsbyconnector/', views.db_analyticsbyconnector, name='db_analyticsbyconnector'),
    path('db_analyticsbyuser/', views.db_analyticsbyuser, name='db_analyticsbyuser'),
    path('db_runningtasks/', views.db_runningtasks, name='db_runningtasks'),
    path('db_highestweightedscoretoday/', views.db_highestweightedscoretoday, name='db_highestweightedscoretoday'),
    path('db_analyticswitherrors/', views.db_analyticswitherrors, name='db_analyticswitherrors'),
]
